---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: omz-sutra-book.tex

      - name: Add and commit PDF document
      - uses: EndBug/add-and-commit@v9 
        with:
          add: omz-sutra-book.pdf
          author_name: Trail Sangha Bot
          author_email: trailsangha@google.com
